const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generate a beautifully formatted PDF document for architecture documentation.
 *
 * @param {object} params
 * @param {object} params.docs            - The documentation JSON object from Azure OpenAI.
 * @param {string} params.docs.overview   - High-level overview.
 * @param {Array<{ name: string, responsibility: string, dependencies: string[] }>} params.docs.components - Components list.
 * @param {string} params.docs.failurePoints - Failure points and modes.
 * @param {string} params.docs.scalingStrategy - Scaling recommendations.
 * @param {string} params.pngPath         - Path to the rendered diagram PNG.
 * @param {string} params.pdfPath         - Target file path for the output PDF.
 * @returns {Promise<void>} Resolves when the PDF file has been fully written.
 */
function generatePdfDocumentation({ docs, pngPath, pdfPath }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, autoFirstPage: true });
    const writeStream = fs.createWriteStream(pdfPath);

    doc.pipe(writeStream);

    // Color Palette
    const PRIMARY_COLOR = '#1e293b'; // Deep Slate
    const SECONDARY_COLOR = '#3b82f6'; // Accent Blue
    const TEXT_COLOR = '#334155'; // Charcoal Body
    const BORDER_COLOR = '#e2e8f0'; // Light Gray border

    // Helper: Draw page header & footer
    function drawPageChrome(pageNumber, totalPages = 3) {
      doc.save();
      // Footer text
      doc.fontSize(8)
         .fillColor('#94a3b8')
         .text('Generated by FlowForge AI Systems Architect', 50, 740, { align: 'left' })
         .text(`Page ${pageNumber} of ${totalPages}`, 50, 740, { align: 'right' });
      doc.restore();
    }

    // Helper: Render multiline bullet-point strings
    function renderBulletPoints(textStr) {
      if (!textStr) return;
      const lines = textStr.split('\n')
                           .map(l => l.trim().replace(/^[•\-\*\s]+/, '').trim())
                           .filter(l => l.length > 0);
      
      lines.forEach(line => {
        doc.fontSize(10)
           .fillColor(TEXT_COLOR)
           .text(`•  ${line}`, { paragraphGap: 6, lineGap: 2 });
      });
    }

    // ==========================================
    // PAGE 1: Overview & Architecture Diagram
    // ==========================================
    
    // Main Document Header
    doc.fontSize(22)
       .fillColor(PRIMARY_COLOR)
       .text('FlowForge AI', { continued: true })
       .fillColor(SECONDARY_COLOR)
       .text(' — Architecture Documentation');

    doc.fontSize(9)
       .fillColor('#64748b')
       .text(`Generated on ${new Date().toLocaleDateString()}`);

    // Horizontal Divider Rule
    doc.moveTo(50, 95)
       .lineTo(562, 95)
       .strokeColor(BORDER_COLOR)
       .lineWidth(1)
       .stroke();

    doc.moveDown(2);

    // Section 1: Overview
    doc.fontSize(14)
       .fillColor(PRIMARY_COLOR)
       .text('1. System Overview', { paragraphGap: 8 });

    renderBulletPoints(docs.overview);
    doc.moveDown(1.5);

    // Section 2: Diagram
    doc.fontSize(14)
       .fillColor(PRIMARY_COLOR)
       .text('2. Architecture Topology Diagram', { paragraphGap: 10 });

    if (fs.existsSync(pngPath)) {
      try {
        doc.image(pngPath, {
          fit: [512, 280],
          align: 'center'
        });
      } catch (err) {
        console.error('[PDF] Error embedding diagram image:', err);
        doc.fontSize(10)
           .fillColor('#ef4444')
           .text('[Error: Could not embed diagram layout image in document]');
      }
    } else {
      doc.fontSize(10)
         .fillColor('#64748b')
         .text('No diagram image available for embedding.');
    }

    drawPageChrome(1);

    // ==========================================
    // PAGE 2: Component Catalog
    // ==========================================
    doc.addPage();

    doc.fontSize(16)
       .fillColor(PRIMARY_COLOR)
       .text('3. Component Catalog', { paragraphGap: 12 });

    if (docs.components && docs.components.length > 0) {
      docs.components.forEach((comp) => {
        // Component Title
        doc.fontSize(11)
           .fillColor(SECONDARY_COLOR)
           .text(comp.name || 'Unnamed Component', { paragraphGap: 4 });

        // Responsibility
        doc.fontSize(10)
           .fillColor(TEXT_COLOR)
           .text(`Responsibility: ${comp.responsibility || 'None specified'}`, { indent: 15, paragraphGap: 2 });

        // Dependencies
        if (comp.dependencies && comp.dependencies.length > 0) {
          const deps = Array.isArray(comp.dependencies) ? comp.dependencies.join(', ') : comp.dependencies;
          doc.fontSize(9)
             .fillColor('#64748b')
             .text(`Dependencies: ${deps}`, { indent: 15, paragraphGap: 8 });
        } else {
          doc.fontSize(9)
             .fillColor('#64748b')
             .text('Dependencies: None', { indent: 15, paragraphGap: 8 });
        }
        doc.moveDown(0.5);
      });
    } else {
      doc.fontSize(10)
         .fillColor(TEXT_COLOR)
         .text('No components cataloged.');
    }

    drawPageChrome(2);

    // ==========================================
    // PAGE 3: Reliability & Scaling
    // ==========================================
    doc.addPage();

    // Section 4: Failure Points
    doc.fontSize(16)
       .fillColor(PRIMARY_COLOR)
       .text('4. Failure Modes & Points of Failure', { paragraphGap: 10 });

    renderBulletPoints(docs.failurePoints);
    doc.moveDown(2);

    // Section 5: Scaling Strategy
    doc.fontSize(16)
       .fillColor(PRIMARY_COLOR)
       .text('5. Scaling & Growth Strategy', { paragraphGap: 10 });

    renderBulletPoints(docs.scalingStrategy);

    drawPageChrome(3);

    // Finalize PDF Document
    doc.end();

    writeStream.on('finish', () => resolve());
    writeStream.on('error', (err) => reject(err));
  });
}

module.exports = {
  generatePdfDocumentation
};
